sudo: required
language: go
go_import_path: github.com/open-policy-agent/gatekeeper
go:
  - "1.13.x"

services:
  - docker

jobs:
  include:
    - stage: "lint, build, unit test, e2e, dev deploy on master, release deploy"
      before_script:
        - GOLANGCILINT_VERSION=1.21.0
        - GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v${GOLANGCILINT_VERSION}
      script:
        - make lint
        - make e2e-bootstrap
        - make e2e-build-load-image IMG=gatekeeper-e2e:latest
        - make patch-image IMG=gatekeeper-e2e:latest USE_LOCAL_IMG=true
        - make deploy
        - make test-e2e
        - echo -e '\n\n======= manager logs =======\n\n' && kubectl logs -n gatekeeper-system -l control-plane=controller-manager
      deploy:
        - provider: script
          skip_cleanup: true
          script: make docker-login && make docker-push-dev IMG=gatekeeper-e2e:latest
          on:
            repo: open-policy-agent/gatekeeper
            branch: master # only push dev image tag for master commits
            tags: false
        - provider: script
          skip_cleanup: true
          script: make docker-login && make docker-push-release IMG=gatekeeper-e2e:latest VERSION=${TRAVIS_TAG}
          on:
            repo: open-policy-agent/gatekeeper
            tags: true # only push release image tag for tags
    - stage: "verify release"
      if: repo = open-policy-agent/gatekeeper AND type != pull_request AND tag IS present
      script:
        - make e2e-bootstrap
        - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
      deploy:
        - provider: script
          skip_cleanup: true
          script: make e2e-verify-release IMG=quay.io/open-policy-agent/gatekeeper:${TRAVIS_TAG} USE_LOCAL_IMG=false
          on:
            repo: open-policy-agent/gatekeeper
            tags: true # only run verify e2e on the released image tag for tags
