apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    admission.gatekeeper.sh/ignore: no-self-managing
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    operation: webhook
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      operation: webhook
  replicas: 1
  template:
    metadata:
      annotations:
        container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
      labels:
        control-plane: controller-manager
        operation: webhook
    spec:
      serviceAccountName: admin
      containers:
      - command:
        - /manager
        args:
          - "--port=8443"
          - "--logtostderr"
          - "--exempt-namespace=gatekeeper-system"
          - "--operation=webhook"
        image: quay.io/open-policy-agent/gatekeeper:v3.1.0-beta.8
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 8888
          name: metrics
          protocol: TCP
        - containerPort: 9090
          name: healthz
          protocol: TCP
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
        securityContext:
          runAsUser: 1000
          runAsGroup: 999
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
  name: audit
  namespace: system
spec:
  containers:
  - args:
    - --operation=audit
    - --logtostderr
    command:
    - /manager
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    image: quay.io/open-policy-agent/gatekeeper:v3.1.0-beta.8
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 9090
    name: audit
    ports:
    - containerPort: 8888
      name: metrics
      protocol: TCP
    - containerPort: 9090
      name: healthz
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /readyz
        port: 9090
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 1000
  serviceAccountName: gatekeeper-admin
  terminationGracePeriodSeconds: 60
