# Default values for annotate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

policy_config:
  name: "conditional-annotation"

policy_parameters:
  matching_annotation: 
    key: "test-mutation"
    value: "true"
  target_annotation:
    key: "foo"
    value: "bar"
  message: "conditional-annotation"