apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: K8sUniqueLabel
metadata:
  name: ns-gk-label-unique
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    label: gatekeeper
