replicas: 1
auditInterval: 60
constraintViolationsLimit: 20
image:
  repository: quay.io/open-policy-agent/gatekeeper
  release: v3.1.0-beta.2
  pullPolicy: IfNotPresent
nodeSelector: {}
tolerations: []
